### ISSUE TITLE
Install compareWith from RStudio docker container

### ISSUE THREAD

**Issue by nfarabullini** [miraisolutions/compareWith#31]
From @vladdsm

> I have started to add this functionality into my docker container stack https://github.com/vladdsm/docker-r-studio
Did not manage to let it work...

Instructions on how to install package when using RStudio docker to follow

----

In order for compareWith to launch Meld inside a containerized RStudio, we need to allow the graphical output from the Docker container to be displayed on the host machine graphical device.

Here is a **working example** on a Linux host machine (we use `rocker/verse` to leverage on many pre-installed packages, but the same works with any image from `rocker/rstudio` up in the Rocker stack).
We use the simplest approach based on mapping the `DISPLAY` environment variable and volume `/tmp/.X11-unix` when creating the container:
``` bash
docker run -d -p 8787:8787 \
  -e USER=me -e PASSWORD=robust_password \
  -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --name rstudio_compareWith_test \
  rocker/verse:3.6.0
```
R and RStudio typically would not get the `DISPLAY` environment variable right, hence we need to add it to `Renviron`
``` bash
docker exec rstudio_compareWith_test bash -c \
  'echo "DISPLAY=${DISPLAY}" >> /usr/local/lib/R/etc/Renviron'
```
Then we install Meld by running
``` bash
docker exec rstudio_compareWith_test bash -c \
  'apt-get update && apt-get install -y --no-install-recommends meld'
```
It should then be possible to install compareWith inside RStudio via
```r
remotes::install_github("miraisolutions/compareWith")
```
and use the addins. This can be tested by checking out a project from GitHub, e.g. `usethis::create_from_github("miraisolutions/compareWith")`.

There will most likely be many `dbus`, `GLib` and `dconf` warnings / errors displayed at the R console when running Meld, this is annoying but should not be problematic.

The example above uses the simplest approach to graphical output from containers. See [this Rocker
issue](https://github.com/rocker-org/rocker/issues/110), this [SO answer](https://stackoverflow.com/questions/25281992/alternatives-to-ssh-x11-forwarding-for-docker-containers/25334301#25334301) and [this article](http://wiki.ros.org/docker/Tutorials/GUI) for some context and alternative, more advanced approaches, especially when user rights and security concerns might be an obstacle to the simplest one.

-----

Cleanup
```bash
    docker rm $(docker stop rstudio_compareWith_test)
```

**Comment by nfarabullini** [comment]
For R version 3.5.1.

Get the image from docker-hub:
```{bash pull}
docker pull rocker/verse:3.5.1
```
then run:
```{bash run}
R_VER=3.5.1
SHARED_DIR=your_shared_directory
docker run -d --restart=always \
  -p 127.0.0.1:$(echo $R_VER | sed 's/[.]//g')0:8787 \
  -e DISABLE_AUTH=true \
  -e USERID=$UID \
  -v $HOME/$SHARED_DIR:/home/rstudio/$SHARED_DIR \
  -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --name rstudio_$R_VER \
  rocker/verse:$R_VER
# R and RStudio are not getting the DISPLAY environment variable
docker exec rstudio_$R_VER bash -c '
echo "DISPLAY=${DISPLAY}" >> /usr/local/lib/R/etc/Renviron
'
```
Now it is possible to install Meld:
```{bash install-meld}
docker exec rstudio_$R_VER bash -c '
apt-get update
apt-get install -y --no-install-recommends meld
'
```
Access RStudio from `http://localhost:3510/`

From console install the sys package:
```{bash install-sys}
remotes::install_github("jeroen/sys")
```
Finally install compareWith:
```{bash install-compareWith}
remotes::install_github("miraisolutions/compareWith")
```

**Comment by riccardoporreca** [comment]
@vladdsm, you may want to first try the _minimal_ example we propose above and then see if this approach indeed works for your case, we'll be happy to have your feedback!

@RolandASc, @nfarabullini, we can wait for some feedback and try this out more at our end, and then  possibly decide if and how we can incorporate this into the package itself (README, vignette, GitHub Wiki, ...). We could also go for a light-weight approach and add short comment in the README referring to this issue, this is an approach I have seen in quite a few places.

**Comment by vladdsm** [comment]
unfortunately this minimal example did not work. At the moment of package installation there is an error: "problem with meld installation"

`Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘compareWith’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Warning: Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
2019-07-19 19:27:21,940 CRITICAL Gtk: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/usr/bin/meld", line 287, in <module>
    setup_resources()
  File "/usr/bin/meld", line 193, in setup_resources
    Gtk.IconTheme.get_default().append_search_path(icon_dir)
AttributeError: 'NoneType' object has no attribute 'append_search_path'
Error: package or namespace load failed for ‘compareWith’:
 .onLoad failed in loadNamespace() for 'compareWith', details:
  call: NULL
  error: Existing Meld installation not working correctly.
Make sure you have a fully functional `meld` installed in your system.
Check instructions in the package README
<https://github.com/miraisolutions/compareWith#installation>.
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/compareWith’
Error: Failed to install 'compareWith' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpgi1En7/file2a210cab25f/compareWith_0.0.1.tar.gz’ had non-zero exit status`

**Comment by vladdsm** [comment]
these are my steps to install meld and compareWith package in this [branch](https://github.com/vladdsm/docker-r-studio/tree/compare_with)

**Comment by riccardoporreca** [comment]
@vladdsm, Note that in the **minimal example** above it is important to run `remotes::install_github("miraisolutions/compareWith")` **from RStudio**. Please make sure this is the case.
Then, if you still have issues, you can

- From RStudio (after re-starting the R session to be safe) check and report Sys.getenv("DISPLAY")
- Try to run at the normal terminal (NOT inside the container) `xhost +`  and re-attempt installing / using compareWith from RStudio. This is giving uncontrolled access to your graphic device, so you want to enable it just for this quick test and then run `xhost -` to revert it. In our case (Ubuntu 18.04, all upgraded), this was not necessary but it might depend on the user setup of your machine.

Note that the setup in your branch probably missing a few key points, I can try to give you a few hints once our minimal example works, to first rule out general problems with your specific setup.

Btw, what is your distro? `hostnamectl` / `lsb_release -a` / `uname -a`

**Comment by RolandASc** [comment]
@riccardoporreca I am closing this due to inactivity. It might still be a good idea to add a short section about this (with a link) in the README as you have suggested above

**Comment by riccardoporreca** [comment]
This is actually covered by https://mirai-solutions.ch/techguides/version-stable-r-development-with-docker.html
